FROM localhost/vllm-cpu-env:latest

# Ensure we're running as root for system configuration
USER root

# Define the path to the entrypoint script
ARG ENTRYPOINT_PATH=image/entrypoint-vllm.sh

# Install basic development tools
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl jq bsdmainutils bc gnuplot \
    libtcmalloc-minimal4 psmisc \
    && rm -rf /var/lib/apt/lists/*

# Configure TCMalloc library
RUN echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4:$LD_PRELOAD' >> /etc/profile

# Install additional dependencies
RUN pip3 install --no-cache-dir \
    transformers \
    accelerate \
    safetensors \
    termplotlib \
    datasets

# Create non-root user for security
RUN useradd -m -u 2000 vllm

# Set the working directory
WORKDIR /app
RUN chown vllm:vllm /app

# Create directories for models and benchmarks
RUN mkdir -p /data/benchmarks && \
   chmod 777 /data/benchmarks

# Switch to non-root user
USER vllm

# Copy the entrypoint script and make it executable
COPY --chown=vllm:vllm ${ENTRYPOINT_PATH} .

# Verify entrypoint script
RUN if [ ! -f "entrypoint-vllm.sh" ]; then echo "Entrypoint script not found!"; exit 1; fi

RUN chmod +x entrypoint-vllm.sh

COPY --chown=vllm:vllm auto_tune_cpu.sh .

RUN chmod +x auto_tune_cpu.sh

# Set the entrypoint
ENTRYPOINT ["./entrypoint-vllm.sh"]

